apiVersion: v1
kind: Secret
metadata:
  name: azdevops
data:
  AZP_TOKEN: 
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: azdevops
data:
  AZP_URL: "https://dev.azure.com/giorgiolasala"
  AZP_POOL: "AKS"