apiVersion: v1
kind: Secret
metadata:
  name: azdevops
data:
  #AZP_TOKEN: 62cyhg355nzykymiefzc6ghoknqyet7mfc7hvrkcqx67wbyjtzea
  AZP_TOKEN: NjJjeWhnMzU1bnp5a3ltaWVmemM2Z2hva25xeWV0N21mYzdodnJrY3F4Njd3YnlqdHplYQ==
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: azdevops
data:
  AZP_URL: "https://dev.azure.com/giorgiolasala"
  AZP_POOL: "AKS"