apiVersion: apps/v1
kind: Deployment
metadata:
  name: azdevops-deployment
  labels:
    app: azdevops-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azdevops-agent
  template:
    metadata:
      labels:
        app: azdevops-agent
    spec:
      containers:
      - name: azdevops-agent
        image: devopsconf.azurecr.io/ubuntu-agent:1.0
        env:
          - name: AZP_URL
            valueFrom:
              configMapKeyRef:
                name: azdevops
                key: AZP_URL
          - name: AZP_POOL
            valueFrom:
              configMapKeyRef:
                name: azdevops
                key: AZP_POOL
          - name: AZP_TOKEN
            valueFrom:
              secretKeyRef:
                name: azdevops
                key: AZP_TOKEN